name: square_app_film
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_spinkit: "^4.1.2"
  carousel_pro: ^1.0.0
  cached_network_image: ^3.0.0
  google_fonts: ^2.0.0
  get:
  video_player: ^2.1.1
  auto_size_text: ^2.1.0
  rxdart: ^0.26.0
  animate_do: ^2.0.0
  url_launcher: ^6.0.3
  flutter_staggered_animations: "^1.0.0"
  smooth_page_indicator: ^0.2.3
  smooth_star_rating: ^1.1.1
  youtube_player_flutter: ^8.0.0
  hive: ^2.0.3
  path_provider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  image_path: "assets/logo/logoA.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  fonts:
     - family: BebasBold
       fonts:
         - asset: assets/BebasNeue-Bold.otf
     - family: BebasRegular
       fonts:
         - asset: assets/BebasNeue-Regular.otf
